### ISSUE TITLE
1.20.x 报 Unsupported operation: Cannot add to an unmodifiable list

### ISSUE THREAD

**Issue by foxsofter** [flutter-thrio/thrio#62]
```
#0      UnmodifiableListMixin.add (dart:_internal/list.dart:114)
#1      ThrioNavigatorImplement.builder.<anonymous closure> (package:thrio/src/navigator/thrio_navigator_implement.dart:81)
#2      _MaterialAppState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/material/app.dart:653)
#3      Builder.build (package:flutter/src/widgets/basic.dart:7118)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4620)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4262)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490)
````

**Comment by foxsofter** [comment]
解决办法是自己传入一个非const的数组
```dart
  Widget build(BuildContext context) => ExcludeSemantics(
        child: MaterialApp(
          builder: ThrioNavigator.builder(entrypoint: widget._entrypoint),
          navigatorObservers: [], // ignore: prefer_const_literals_to_create_immutables
          home: NavigatorHome(),
          theme: ThemeData(
            pageTransitionsTheme: const PageTransitionsTheme(builders: {
              TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
              TargetPlatform.android: CupertinoPageTransitionsBuilder(),
            }),
          ),
        ),
      );
```
这是1.20.1 Flutter SDK代码重构之后navigatorObservers取了默认值为const[]引起的，暂时没有太好的办法绕过

**Comment by foxsofter** [comment]
已通过继承 MaterialApp 的方式绕过
